"""init added

Revision ID: 67a74033ac20
Revises: f5415658a57a
Create Date: 2019-09-30 20:13:48.320681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a74033ac20'
down_revision = 'f5415658a57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
