"""new removed

Revision ID: 7744bb71e01c
Revises: e638c1b793dd
Create Date: 2019-10-01 23:11:08.152196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7744bb71e01c'
down_revision = 'e638c1b793dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweetmeta', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweetmeta', sa.Column('new', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
