"""alembic change

Revision ID: 8db337e39f5d
Revises: 13ccd0678bc0
Create Date: 2019-09-30 12:57:49.659763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db337e39f5d'
down_revision = '13ccd0678bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
