"""new added

Revision ID: e638c1b793dd
Revises: 67a74033ac20
Create Date: 2019-10-01 23:10:02.752714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e638c1b793dd'
down_revision = '67a74033ac20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweetmeta', sa.Column('new', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweetmeta', 'new')
    # ### end Alembic commands ###
