"""column removed

Revision ID: f5415658a57a
Revises: 9e3cb0c92343
Create Date: 2019-09-30 19:27:31.568742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5415658a57a'
down_revision = '9e3cb0c92343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tweetmeta', 'extra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweetmeta', sa.Column('extra', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
